<?php
/******************************************************
 * @package Magento 2 Membership
 * @author http://www.magefox.com
 * @copyright (C) 2018 - Magefox.Com
 * @license MIT
 *******************************************************/
?>
<?php
/**
 * @var $block \Magefox\Membership\Block\Account\Dashboard\Status
 */
?>
<div class="block block-dashboard-vip">
    <div class="block-title">
        <strong><?php /* @escapeNotVerified */ echo __('Membership Status') ?></strong>
    </div>
    <div class="block-content">
        <p><?php /* @escapeNotVerified */  echo __('You have %1 days left of your Membership. Expire in %2.', $block->getDaysLeft(), $block->getExpiry()) ?></p>
    </div>
</div>
